### PR TITLE
fix: request a password to change sensitive user data

### LINKED ISSUE #5213: Sensitive actions should authenticate with additional security check
### Checklist

- [x] This is a bug report, not a question.
- [x] I have searched on the [issue tracker](https://github.com/filebrowser/filebrowser/issues?q=is%3Aissue) for my bug.
- [x] I am running the latest [FileBrowser version](https://github.com/filebrowser/filebrowser/releases) or have an issue updating.

### Version

```Text
All
```

### Description

> Some sensitive actions (changing a user's password, allowing a user to use the command execution feature) can be used by an authenticated user without an additional security prompt like reentering the password. This means that those actions can be misused via XSS or a local attacker with access to an unlocked device.

Thanks @mtausig for the report.

### What did you expect to happen?

_No response_

### What actually happened?

_No response_

### Reproduction Steps

_No response_

### Files

_No response_

### PR DESCRIPTION
**Pull request by ArielLeyva**
## Description
When modifying sensitive user data (such as passwords, executing commands, registering new users, etc.), the authenticated user's password is requested to validate the action.

This only applies if the authentication method is "json" (JSON Web Token). With the "proxy" authentication method, it would require validation that is outside the scope of the Filebrowser backend. It could also apply to the "hook" authentication method, but this could cause confusion for Filebrowser users.

## Additional Information
Closes https://github.com/filebrowser/filebrowser/issues/5213

## Checklist

Before submitting your PR, please indicate which issues are either fixed or closed by this PR. See [GitHub Help: Closing issues using keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

- [x] I am aware the project is currently in maintenance-only mode. See [README](https://github.com/filebrowser/community/blob/master/README.md)
- [x] I am aware that translations MUST be made through [Transifex](https://app.transifex.com/file-browser/file-browser/) and that this PR is NOT a translation update
- [x] I am making a PR against the `master` branch.
- [x] I am sure File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).

### CODE REVIEW

File: errors/errors.go [hunk 1]
```diff
@@ -6,22 +6,23 @@ import (
...
+	ErrScopeIsRelative          = errors.New("scope is a relative path")
+	ErrInvalidDataType          = errors.New("invalid data type")
+	ErrIsDirectory              = errors.New("file is directory")
+	ErrInvalidOption            = errors.New("invalid option")
+	ErrInvalidAuthMethod        = errors.New("invalid auth method")
+	ErrPermissionDenied         = errors.New("permission denied")
+	ErrInvalidRequestParams     = errors.New("invalid request params")
+	ErrSourceIsParent           = errors.New("source is parent")
+	ErrRootUserDeletion         = errors.New("user with id 1 can't be deleted")
+	ErrCurrentPasswordIncorrect = errors.New("the current password is incorrect")
```
Comment (ArielLeyva) [inline errors/errors.go:25]: Error returned when validating the logged-in user's password if validation fails

File: frontend/src/api/users.ts [hunk 2]
```diff
@@ -8,12 +8,13 @@ export async function get(id: number) {
...
 }
 
-export async function create(user: IUser) {
+export async function create(user: IUser, currentPassword: string) {
   const res = await fetchURL(`/api/users`, {
     method: "POST",
     body: JSON.stringify({
       what: "user",
       which: [],
+      current_password: currentPassword,
```
Comment (ArielLeyva) [inline frontend/src/api/users.ts:17]: Send current password entered in the form

File: frontend/src/api/users.ts [hunk 3]
```diff
@@ -25,12 +26,17 @@ export async function create(user: IUser) {
...
+  user: Partial<IUser>,
+  which = ["all"],
+  currentPassword: string | null = null
+) {
   await fetchURL(`/api/users/${user.id}`, {
     method: "PUT",
     body: JSON.stringify({
       what: "user",
       which: which,
+      ...(currentPassword != null ? { current_password: currentPassword } : {}),
```
Comment (ArielLeyva) [inline frontend/src/api/users.ts:39]: Send current password entered in the form (only if it was sent in the argument)

File: frontend/src/types/settings.d.ts [hunk 4]
```diff
@@ -5,6 +5,7 @@ interface ISettings {
   minimumPasswordLength: number;
   userHomeBasePath: string;
   defaults: SettingsDefaults;
+  authMethod: string;
```
Comment (ArielLeyva) [inline frontend/src/types/settings.d.ts:8]: Include authentication type in the settings returned to the frontend to show/hide the "current password" field depending on the authentication type

File: frontend/src/views/settings/Profile.vue [hunk 5]
```diff
@@ -131,6 +142,9 @@ onMounted(async () => {
   dateFormat.value = authStore.user.dateFormat;
   aceEditorTheme.value = authStore.user.aceEditorTheme;
   layoutStore.loading = false;
+  const { authMethod } = await settings.get();
+  isCurrentPasswordRequired.value = authMethod == "json";
```
Comment (ArielLeyva) [inline frontend/src/views/settings/Profile.vue:146]: Display the "current password" field only if the authentication type is JSON

File: http/users.go [hunk 6]
```diff
@@ -117,6 +118,12 @@ var userPostHandler = withAdmin(func(w http.ResponseWriter, r *http.Request, d *
 		return http.StatusBadRequest, err
 	}
 
+	if d.settings.AuthMethod == auth.MethodJSONAuth {
```
Comment (ArielLeyva) [inline http/users.go:121]: Apply verification if the authentication type is JSON

File: http/users.go [hunk 7]
```diff
@@ -153,6 +160,27 @@ var userPutHandler = withSelfOrAdmin(func(w http.ResponseWriter, r *http.Request
...
```
Comment (ArielLeyva) [inline http/users.go:163]: Apply verification if the authentication type is JSON

File: http/users.go [hunk 8]
```diff
@@ -153,6 +160,27 @@ var userPutHandler = withSelfOrAdmin(func(w http.ResponseWriter, r *http.Request
...
+		var sensibleFields = map[string]struct{}{
```
Comment (ArielLeyva) [inline http/users.go:164]: Define the sensitive fields. If these are sent from the frontend for updating, validation must be applied.

**Review by hacdias — APPROVED** [review]
Thank you!

**Comment by Mask-Vip** [comment]
After upgrading to the latest version, although you need to confirm the current password again when creating or modifying user information, deleting users still does not require the current password! Deleting users should also be a sensitive operation, right?

**Comment by ArielLeyva** [comment]
> After upgrading to the latest version, although you need to confirm the current password again when creating or modifying user information, deleting users still does not require the current password! Deleting users should also be a sensitive operation, right?

Yes, I'll open a PR with this change.

**Comment by Mask-Vip** [comment]
> > After upgrading to the latest version, although you need to confirm the current password again when creating or modifying user information, deleting users still does not require the current password! Deleting users should also be a sensitive operation, right?
> 
> Yes, I'll open a PR with this change.

Thank you very much for your reply and efforts.
