### PR TITLE
Some fixes

### LINKED ISSUE #1497: Video preview
播放不了1080p的视频 一直加载
6BPY{6(UT%})XEYOXRIW5O7

### PR DESCRIPTION
**Pull request by ramiresviana**
### fix: file caching directive
Using etag header with `http.ServeContent` causes unexpected behavior. The etag was removed in favor of the `http.ServeContent` implementation. fixes #1497

### feat: open file option on preview
Allows users to open the file when the preview is not available.

### CODE REVIEW

File: http/static.go [hunk 1]
```diff
@@ -77,7 +77,7 @@ func handleWithStaticData(w http.ResponseWriter, _ *http.Request, d *data, fSys
 		return http.StatusInternalServerError, err
 	}
 
-	data["Json"] = string(b)
+	data["Json"] = strings.ReplaceAll(string(b), `'`, `\'`)
```
Comment (o1egl) [inline http/static.go:80]: Encoded json is already escaped. Why this is needed?

File: http/preview.go [hunk 2]
```diff
@@ -80,33 +80,30 @@ func handleImagePreview(w http.ResponseWriter, r *http.Request, imgSvc ImgServic
...
 	cacheKey := previewCacheKey(file.Path, file.ModTime.Unix(), previewSize)
 	cachedFile, ok, err := fileCache.Load(r.Context(), cacheKey)
 	if err != nil {
 		return errToStatus(err), err
 	}
 	if ok {
-		_, _ = w.Write(cachedFile)
-		return 0, nil
-	}
+		resizedImage = cachedFile
```
Comment (o1egl) [inline http/preview.go]: It can be rewritten to:

```go 
resizedImage, ok, err := fileCache.Load(r.Context(), cacheKey)
if err != nil {
    return errToStatus(err), err
}
if !ok {
    resizedImage, err = createPreview(imgSvc, fileCache, file, previewSize, enableThumbnails, resizePreview)
    if err != nil { 
        return errToStatus(err), err
    }
}
```

File: http/static.go (hunk 1 above)
Comment (ramiresviana) [reply http/static.go:80]: It escapes double quotes but not single quotes. Since single quotes is used as delimiter in the index template, it needs to be escaped manually.

https://github.com/filebrowser/filebrowser/blob/25c87883908babde073390a2e2320a8e5880a87c/frontend/public/index.html#L33
