### PR TITLE
fix: lookup directory name if blank when downloading shared directory

### LINKED ISSUE #5255: Folder Sharing Packaging Download Naming Error
### Checklist

- [x] This is a bug report, not a question.
- [x] I have searched on the [issue tracker](https://github.com/filebrowser/filebrowser/issues?q=is%3Aissue) for my bug.
- [x] I am running the latest [FileBrowser version](https://github.com/filebrowser/filebrowser/releases) or have an issue updating.

### Version

```Text
V2.36.0

version amd64 centos7
```

### Description

Share a folder via a link and then download the package of this folder, the name of the package is always fixed to “ZIP”.

Manually rename the package to “XXX.ZIP” and it unpacks fine, it just looks like a naming error.

### What did you expect to happen?

fixes

### What actually happened?

bug

### Reproduction Steps

bug

### Files

_No response_

### PR DESCRIPTION
**Pull request by Rmiller5466**
## Description

When downloading a shared directory, the fileinfo was being overwritten to where the directory in question would become the new fs root.  This lead to file.Name = "" and file.Path = "/", hence the bug of downloading a file with the name ".zip" ("" + ".zip").  This has been fixed by doing an fs.Stat(".") to get the current directories name under the circumstances where file.Name is empty.  

## Checklist

closes #5255

- [X] I am aware the project is currently in maintenance-only mode. See [README](https://github.com/filebrowser/community/blob/master/README.md)
- [X] I am aware that translations MUST be made through [Transifex](https://app.transifex.com/file-browser/file-browser/) and that this PR is NOT a translation update
- [X] I am making a PR against the `master` branch.
- [X] I am sure File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).

### CODE REVIEW

File: http/raw.go [hunk 1]
```diff
@@ -177,7 +177,18 @@ func rawDirHandler(w http.ResponseWriter, r *http.Request, d *data, file *files.
...
+			name = file.Name
+		} else {
+			// This should indicate that the fs root is the directory being downloaded, lookup its name
+
+			actual, statErr := file.Fs.Stat(".")
+			if statErr != nil {
+				return http.StatusInternalServerError, statErr
+			}
+			name = actual.Name()
+		}
```
Comment (hacdias) [inline http/raw.go:191]: I'm thinking about this. It is possible to download multiple directories at once, and I think that is one of the cases where an empty name is happening.

I think we should use a static name here, maybe just `download`.

I want to avoid showing the root directory for this reason here: https://github.com/filebrowser/filebrowser/issues/3794

Comment (Rmiller5466) [reply http/raw.go:191]: It's important to distinguish the two ways downloads can be done (atleast that I'm aware of): 

1) selecting file(s) directly in the UI and clicking the download button 
2) selecting a single file and using the "share with" option.

This empty name bug was only occurring on that second method.  When downloading multiple directories / files in the UI I am observing it being saved as "\_{PARENT_DIR}.zip".  When downloading a single file it is downloading as "{FILE_NAME.zip}".  To be consistent with the default (non-share) download button UI, this could also be updated to "\_{PARENT_DIR}.zip", or to your point about avoiding the root directory we could change both of these to be a generic "download.zip".  Regardless I think we should do the same for each for consistency.  

I personally lean more towards leaving the parent directory name as the default download title - as a user I feel it's more immediately clear that I'm downloading what I expected rather than having to unzip / preview the file after it has finished to ensure I didn't download the wrong thing.

Comment (hacdias) [reply http/raw.go:191]: Let's keep it as-is then. It can always be changed later.
