### PR TITLE
fix: properly surface config parse errors

### LINKED ISSUE #5821: Malformed config file incorrectly reported as "no config being used"
### Checklist

- [x] This is a bug report, not a question.
- [x] I have searched on the [issue tracker](https://github.com/filebrowser/filebrowser/issues?q=is%3Aissue) for my bug.
- [x] I am running the latest [FileBrowser version](https://github.com/filebrowser/filebrowser/releases) or have an issue updating.

### Version

```Text
v2.61.2
```

### Description

If the configuration file exists but is invalid, filebrowser reports that no configuration file is being used instead of surfacing the parsing error from Viper.

### What did you expect to happen?

If the configuration file exists but is invalid, the application should report the configuration parsing error.

### What actually happened?

The application reports that no configuration file is being used, masking the underlying parse error.

### Reproduction Steps

1. Run `echo 'root = /unquoted/path' > .filebrowser.toml`
2. Run `go run .`
3. Observe output

### Files

_No response_

### PR DESCRIPTION
**Pull request by apkatsikas**
## Description

When the configuration file was malformed, the application would incorrectly report that no configuration was being used.

This happened because the error check used `errors.Is` instead of `errors.As`, which prevented `viper.ConfigParseError` from being properly detected.

This change fixes the error detection so configuration parsing errors are correctly surfaced to the user.

## Additional Information

Closes https://github.com/filebrowser/filebrowser/issues/5821

## Checklist

- [x] I am aware the project is currently in maintenance-only mode. See [README](https://github.com/filebrowser/community/blob/master/README.md)
- [x] I am aware that translations MUST be made through [Transifex](https://app.transifex.com/file-browser/file-browser/) and that this PR is NOT a translation update
- [x] I am making a PR against the `master` branch.
- [x] I am sure File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).

### CODE REVIEW

File: cmd/utils.go [hunk 1]
```diff
@@ -118,7 +118,9 @@ func initViper(cmd *cobra.Command) (*viper.Viper, error) {
 
 	// Read in configuration
 	if err := v.ReadInConfig(); err != nil {
-		if errors.Is(err, viper.ConfigParseError{}) {
+
+		var parseErr viper.ConfigParseError
+		if errors.As(err, &parseErr) {
```
Comment (hacdias) [inline cmd/utils.go]: Wouldn't this work?

```suggestion
		if errors.Is(err, &viper.ConfigParseError{}) {
```

Comment (apkatsikas) [reply cmd/utils.go]: @hacdias yes, I tried this previously and it worked - I will push the one-liner update.

Comment (apkatsikas) [reply cmd/utils.go]: https://github.com/filebrowser/filebrowser/pull/5822/changes/3b69e77d187f2178bb2f4c7346ab2b4c1b1ef339 fixed.
