### PR TITLE
fix: request current password when deleting users

### LINKED ISSUE #5666: Normal user cannot change password
### Checklist

- [x] This is a bug report, not a question.
- [x] I have searched on the [issue tracker](https://github.com/filebrowser/filebrowser/issues?q=is%3Aissue) for my bug.
- [x] I am running the latest [FileBrowser version](https://github.com/filebrowser/filebrowser/releases) or have an issue updating.

### Version

```Text
linux-386-filebrowser.tar.gz 2.53.1
```

### Description

When normal user enter setting:
index-CXpROGsN.js:2  GET http://1.1.1.1:8080/api/settings 403 (Forbidden)
ft @ index-CXpROGsN.js:2
Cn @ index-CXpROGsN.js:2
ji @ index-CXpROGsN.js:2
(anonymous) @ index-CXpROGsN.js:2
(anonymous) @ i18n-DHjrTBzE.js:1
Li @ i18n-DHjrTBzE.js:1
$t @ i18n-DHjrTBzE.js:1
e.__weh.e.__weh @ i18n-DHjrTBzE.js:1
eo @ i18n-DHjrTBzE.js:1
qe @ i18n-DHjrTBzE.js:1
mount @ i18n-DHjrTBzE.js:1
e.mount @ i18n-DHjrTBzE.js:1
(anonymous) @ index-CXpROGsN.js:2
Promise.then
(anonymous) @ index-CXpROGsN.js:2
i18n-DHjrTBzE.js:1 StatusError: 403 Forbidden

    at ft (index-CXpROGsN.js:2:132328)
    at async Cn (index-CXpROGsN.js:2:132464)
    at async index-CXpROGsN.js:2:814090

### What did you expect to happen?

change the password

### What actually happened?

error on console and password not change

### Reproduction Steps

Image

### Files

_No response_

### PR DESCRIPTION
**Pull request by ArielLeyva**
## Description
When deleting a user, you must enter the password of the logged-in user (administrator) because it is a "sensitive" action. (https://github.com/filebrowser/filebrowser/pull/5629#issuecomment-3715931728)
The logic for returning the authentication method was separated into a separate endpoint without administrator permissions to allow non-administrator users to modify their password (currently it does not allow modification since the "current password" field is not shown in the form because the method to get all settings returns 403 for non-administrator users): Issue https://github.com/filebrowser/filebrowser/issues/5666

## Additional Information
Closes https://github.com/filebrowser/filebrowser/issues/5666

## Checklist

Before submitting your PR, please indicate which issues are either fixed or closed by this PR. See [GitHub Help: Closing issues using keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

- [x] I am aware the project is currently in maintenance-only mode. See [README](https://github.com/filebrowser/community/blob/master/README.md)
- [x] I am aware that translations MUST be made through [Transifex](https://app.transifex.com/file-browser/file-browser/) and that this PR is NOT a translation update
- [x] I am making a PR against the `master` branch.
- [x] I am sure File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).

### CODE REVIEW

File: frontend/src/views/settings/Profile.vue [hunk 1]
```diff
@@ -142,7 +142,7 @@ onMounted(async () => {
   dateFormat.value = authStore.user.dateFormat;
   aceEditorTheme.value = authStore.user.aceEditorTheme;
   layoutStore.loading = false;
-  const { authMethod } = await settings.get();
+  const { authMethod } = await settings.getAuthMethod();
```
Comment (ramiresviana) [inline frontend/src/views/settings/Profile.vue]: This information is already available and doesn't need to be fetched again, see: https://github.com/filebrowser/filebrowser/blob/b9ac45d5dac4b4eb2ba364629090fbf306cffd2b/frontend/src/utils/constants.ts#L12

**Review by ramiresviana — CHANGES_REQUESTED** [review]

File: frontend/src/views/settings/Profile.vue (hunk 1 above)
Comment (ArielLeyva) [reply frontend/src/views/settings/Profile.vue]: > This information is already available and doesn't need to be fetched again, see:
> 
> https://github.com/filebrowser/filebrowser/blob/b9ac45d5dac4b4eb2ba364629090fbf306cffd2b/frontend/src/utils/constants.ts#L12

Oh, thank you so much for the clarification, I've made the correction.

File: frontend/src/api/users.ts [hunk 2]
```diff
@@ -42,8 +42,15 @@ export async function update(
...
 
-export async function remove(id: number) {
+export async function remove(
+  id: number,
+  currentPassword: string | null = null
+) {
   await fetchURL(`/api/users/${id}`, {
     method: "DELETE",
+    body: JSON.stringify({
+      what: "user",
```
Comment (hacdias) [inline frontend/src/api/users.ts]: Is this necessary?

Comment (ArielLeyva) [reply frontend/src/api/users.ts]: That's right, it's not necessary to send this field to delete a user; I've modified the code so that it's not necessary to send it.

**Review by hacdias — APPROVED** [review]
