### PR TITLE
fix: share page preview items to contain baseUrl

### LINKED ISSUE #5491: Thumbnail URLs missing baseURL prefix in shared folder page
### Checklist

- [x] This is a bug report, not a question.
- [x] I have searched on the [issue tracker](https://github.com/filebrowser/filebrowser/issues?q=is%3Aissue) for my bug.
- [x] I am running the latest [FileBrowser version](https://github.com/filebrowser/filebrowser/releases) or have an issue updating.

### Version

```Text
2.44.1
```

### Description

I found a bug in FileBrowser related to shared folders.
When I share a folder, the preview thumbnails on the shared page fail to load properly.

In my setup, I’ve configured a baseURL and use Caddy to reverse proxy all requests with the /sysFile prefix to FileBrowser.
However, the preview image URLs on the shared page don’t include this configured baseURL prefix, so the browser tries to fetch the images without /sysFile in the path, resulting in broken thumbnails.

### What did you expect to happen?

The preview image URLs on the shared page should automatically include the configured baseURL prefix (e.g. /sysFile/api/public/...) so that thumbnails load correctly when FileBrowser is served under a path prefix or reverse proxy.

### What actually happened?

The preview image URLs are missing the configured baseURL prefix.
As a result, the browser tries to load images from incorrect paths (without /sysFile), and all thumbnails fail to display.

### Reproduction Steps

Set a baseURL in FileBrowser config (e.g. /sysFile).

Use Caddy or another reverse proxy to forward requests from /sysFile to FileBrowser.

Open FileBrowser and create a public share link for any folder containing image files.

Visit the shared link and check the thumbnails in the file list.

### Files

_No response_

### PR DESCRIPTION
**Pull request by jagadam97**
## Description

In this PR i have changed the logic of how preview's URL are generated to respect the base URL.

rather than replacing the URL of share which will be regex operation i am building the URL using path and hash.

Screenshot_2025-11-11_06-21-22

## Additional Information

Closes #5491

## Checklist

Before submitting your PR, please indicate which issues are either fixed or closed by this PR. See [GitHub Help: Closing issues using keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

- [x] I am aware the project is currently in maintenance-only mode. See [README](https://github.com/filebrowser/community/blob/master/README.md)
- [x] I am aware that translations MUST be made through [Transifex](https://app.transifex.com/file-browser/file-browser/) and that this PR is NOT a translation update
- [x] I am making a PR against the `master` branch.
- [x] I am sure File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).

### CODE REVIEW

File: frontend/src/components/settings/AceEditorTheme.vue [hunk 1]
```diff
@@ -1,5 +1,9 @@
 <template>
-  <select name="selectAceEditorTheme" v-on:change="change" :value="aceEditorTheme">
```
Comment (jagadam97) [inline frontend/src/components/settings/AceEditorTheme.vue:2]: Had to add this because lint-frontend is throwing warning.
Screenshot_2025-11-11_06-20-19

**Review by hacdias — APPROVED** [review]
Thank you!
