### PR TITLE
fix(auth): prevent integer overflow in logout timer using safeTimeout

### LINKED ISSUE #5461: Inadvertently logged out because of timeout integer overflow
### Checklist

- [x] This is a bug report, not a question.
- [x] I have searched on the [issue tracker](https://github.com/filebrowser/filebrowser/issues?q=is%3Aissue) for my bug.
- [x] I am running the latest [FileBrowser version](https://github.com/filebrowser/filebrowser/releases) or have an issue updating.

### Version

```Text
v2.44.0
```

### Description

After deploying Filebrowser v2.44.0 I am automatically logged out and the error "You have been logged out due to inactivity." is shown.
When trying to login with the correct credentials the message is shown again. When trying to login with the wrong credentials it correctly shows "Wrong credentials".
Redeploying a previous version (v2.43.0) fixes the issue.

### What did you expect to happen?

Expected a successful logjn.

### What actually happened?

The error "You have been logged out due to inactivity." is shown and no login happens. The call to /api/login returns 200 OK.
I might be related to commit e6c674b (https://github.com/filebrowser/filebrowser/commit/e6c674b3c616831942c4d4aacab0907d58003e23).

### Reproduction Steps

Update to current version and try to login. I am using Firefox Browser on MacOs.

### Files

_No response_

### PR DESCRIPTION
**Pull request by ArielLeyva**
## Description
Closes https://github.com/filebrowser/filebrowser/issues/5461
This PR introduces a new setSafeTimeout utility to replace the direct use of setTimeout when scheduling automatic user logout based on JWT expiration.

## Additional Information
- Replaced the existing setTimeout call in parseToken() with a safer implementation that avoids integer overflow issues when the delay exceeds the 32-bit limit (~24.8 days).
- The new setSafeTimeout function divides long timeouts into smaller intervals (e.g., 1 day each) and checks the remaining time recursively until the total delay has passed.
- Ensures consistent behavior across browsers, mobile WebViews, and other runtime environments that may impose shorter timeout limits.

## Checklist

Before submitting your PR, please indicate which issues are either fixed or closed by this PR. See [GitHub Help: Closing issues using keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

- [x] I am aware the project is currently in maintenance-only mode. See [README](https://github.com/filebrowser/community/blob/master/README.md)
- [x] I am aware that translations MUST be made through [Transifex](https://app.transifex.com/file-browser/file-browser/) and that this PR is NOT a translation update
- [x] I am making a PR against the `master` branch.
- [x] I am sure File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).

### CODE REVIEW

File: frontend/src/api/utils.ts [hunk 1]
```diff
@@ -91,3 +91,21 @@ export function createURL(endpoint: string, searchParams = {}): string {
 
   return url.toString();
 }
+
+export function setSafeTimeout(callback: () => void, delay: number): number {
+  const MAX_DELAY = 86_400_000;
```
Comment (hacdias) [inline frontend/src/api/utils.ts:96]: Another idea would be to use `Number.MAX_SAFE_INTEGER`. Is there a reason not to? Then it'll be architecture dependent

Comment (ArielLeyva) [reply frontend/src/api/utils.ts:96]: It's a good idea but the value stored in the `Number.MAX_SAFE_INTEGER` constant exceeds the limit imposed by `setTimeout` (which is **32 bits** in most cases or **16 bits** in specific contexts like _microcontrollers_). In the [Node.js documentation (25.0.0)](https://nodejs.org/docs/latest/api/timers.html#settimeoutcallback-delay-args) it talks about the 32-bit limit (`2147483647`), if this value is exceeded Node.js internally sets the timer to 1 and that's why it executes instantly. I decided to use the value `86_400_000` since it is a fairly safe maximum limit even in small environments.

Comment (hacdias) [reply frontend/src/api/utils.ts:96]: Ah, you're correct. MDN says browsers do the same; https://developer.mozilla.org/en-US/docs/Web/API/Window/setTimeout#maximum_delay_value
