### PR TITLE
fix: show login when session token expires

### LINKED ISSUE #5212: Session timeout should trigger automatic redirect to login page
### Checklist

- [x] This is a bug report, not a question.
- [x] I have searched on the [issue tracker](https://github.com/filebrowser/filebrowser/issues?q=is%3Aissue) for my bug.
- [x] I am running the latest [FileBrowser version](https://github.com/filebrowser/filebrowser/releases) or have an issue updating.

### Version

```Text
All
```

### Description

> A session timeout should trigger an automatic redirect to the login page. Without this, sensitive information (like the content of an opened file) will be visible indefinitely in the browser.

Thanks @mtausig for the report.

### What did you expect to happen?

_No response_

### What actually happened?

_No response_

### Reproduction Steps

_No response_

### Files

_No response_

### PR DESCRIPTION
**Pull request by ArielLeyva**
Closes https://github.com/filebrowser/filebrowser/issues/5212

## Description

Implements automatic frontend redirection to the login page when the authentication token expires, based on the backend’s token-expiration-time setting.

## Checklist

Before submitting your PR, please indicate which issues are either fixed or closed by this PR. See [GitHub Help: Closing issues using keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

- [x] I am aware the project is currently in maintenance-only mode. See [README](https://github.com/filebrowser/community/blob/master/README.md)
- [x] I am aware that translations MUST be made through [Transifex](https://app.transifex.com/file-browser/file-browser/) and that this PR is NOT a translation update
- [x] I am making a PR against the `master` branch.
- [x] I am sure File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).

### CODE REVIEW

File: http/auth.go [hunk 1]
```diff
@@ -214,8 +214,13 @@ func printToken(w http.ResponseWriter, _ *http.Request, d *data, user *users.Use
...
 
-	w.Header().Set("Content-Type", "text/plain")
-	if _, err := w.Write([]byte(signed)); err != nil {
+	response := map[string]interface{}{
+		"token":     signed,
+		"expiresAt": claims.ExpiresAt.Time.Format(time.RFC3339), // fecha en string ISO 8601
+	}
+
+	w.Header().Set("Content-Type", "application/json")
+	if err := json.NewEncoder(w).Encode(response); err != nil {
```
Comment (ramiresviana) [inline http/auth.go]: This change is unnecessary, the frontend already has access to the expiration timestamp through the `exp` claim in the token.

Comment (ArielLeyva) [reply http/auth.go]: Appreciate it! I didn’t know `jwt-decode` had that property. I fixed the frontend and rolled back the backend change.

**Review by ramiresviana — COMMENTED** [review]
Since the logout is happening without user interaction, adding a message to inform the user they’ve been logged out would make the behavior clearer. Also, please ensure the code passes linter checks by running `pnpm run lint` to avoid errors when this PR is merged.

**Comment by ArielLeyva** [comment]
> Since the logout is happening without user interaction, adding a message to inform the user they’ve been logged out would make the behavior clearer. Also, please ensure the code passes linter checks by running `pnpm run lint` to avoid errors when this PR is merged.

Perfect, I made that change and I had no problems with `pnpm running lint`.

**Review by ramiresviana — COMMENTED** [review]
You have to fix the lint warnings

```
frontend > pnpm run lint

> filebrowser-frontend@3.0.0 lint /home/filebrowser/frontend
> eslint src/


/home/filebrowser/frontend/src/types/user.d.ts
  66:40  warning  Insert `⏎`  prettier/prettier

/home/filebrowser/frontend/src/utils/auth.ts
   27:14  warning  Replace `'inactivity'` with `"inactivity"`  prettier/prettier
  116:7   warning  Insert `·`                                  prettier/prettier
  117:20  warning  Delete `·`                                  prettier/prettier
  118:24  warning  Delete `·`                                  prettier/prettier
  119:43  warning  Insert `,`                                  prettier/prettier
  122:20  warning  Delete `·`                                  prettier/prettier
  125:6   warning  Delete `⏎····`                              prettier/prettier

/home/filebrowser/frontend/src/views/Login.vue
    6:55  warning  Replace `{{t(`login.logout_reasons.${reason}`)}}` with `⏎········{{·t(`login.logout_reasons.${reason}`)·}}⏎······`  prettier/prettier
   74:28  warning  Replace `'logout-reason'` with `"logout-reason"`                                                                    prettier/prettier
  130:10  warning  Insert `⏎`                                                                                                          prettier/prettier

✖ 11 problems (0 errors, 11 warnings)
  0 errors and 11 warnings potentially fixable with the `--fix` option.
```

**Comment by ArielLeyva** [comment]
> You have to fix the lint warnings
> 
> ```
> frontend > pnpm run lint
> 
> > filebrowser-frontend@3.0.0 lint /home/filebrowser/frontend
> > eslint src/
> 
> 
> /home/filebrowser/frontend/src/types/user.d.ts
>   66:40  warning  Insert `⏎`  prettier/prettier
> 
> /home/filebrowser/frontend/src/utils/auth.ts
>    27:14  warning  Replace `'inactivity'` with `"inactivity"`  prettier/prettier
>   116:7   warning  Insert `·`                                  prettier/prettier
>   117:20  warning  Delete `·`                                  prettier/prettier
>   118:24  warning  Delete `·`                                  prettier/prettier
>   119:43  warning  Insert `,`                                  prettier/prettier
>   122:20  warning  Delete `·`                                  prettier/prettier
>   125:6   warning  Delete `⏎····`                              prettier/prettier
> 
> /home/filebrowser/frontend/src/views/Login.vue
>     6:55  warning  Replace `{{t(`login.logout_reasons.${reason}`)}}` with `⏎········{{·t(`login.logout_reasons.${reason}`)·}}⏎······`  prettier/prettier
>    74:28  warning  Replace `'logout-reason'` with `"logout-reason"`                                                                    prettier/prettier
>   130:10  warning  Insert `⏎`                                                                                                          prettier/prettier
> 
> ✖ 11 problems (0 errors, 11 warnings)
>   0 errors and 11 warnings potentially fixable with the `--fix` option.
> ```

Code has been reformatted to comply with Prettier's guidelines. 
Appreciate your guidance throughout the process—really helped clarify a few things.

**Review by hacdias — APPROVED** [review]
Thank you both!
